spring.datasource.url=jdbc:postgresql://3.26.176.45:5432/telusko
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver